import XLSX from "xlsx";
import { Document, Paragraph, TextRun, HeadingLevel, Packer } from "docx";
import htmlPdf from "html-pdf-node";

export const escapeHtml = (s) => String(s || "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const inlineFmt = (str) => {
  return escapeHtml(str)
    .replace(/\*\*(.*?)\*\*/g, '<strong style="color:#0f172a;font-weight:700;">$1</strong>')
    .replace(/\*(.*?)\*/g, "<em>$1</em>");
};

export function formatDocumentToHtml(content) {
  const lines = content.split("\n");
  const parts = [];
  let inList = false;
  const dateStr = new Date().toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });

  for (const raw of lines) {
    const l = raw.trim();
    if (!l) {
      if (inList) { parts.push("</ul>"); inList = false; }
      continue;
    }
    if (l.startsWith("# ")) {
      if (inList) { parts.push("</ul>"); inList = false; }
      parts.push(`<h1 style="font-size:22px;font-weight:800;color:#0f172a;margin:14px 0 6px 0;line-height:1.2;">${inlineFmt(l.slice(2))}</h1><div style="height:3px;width:40px;background:#4f46e5;border-radius:2px;margin-bottom:14px;"></div>`);
    } else if (l.startsWith("## ")) {
      if (inList) { parts.push("</ul>"); inList = false; }
      parts.push(`<h2 style="font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:0.8px;color:#1e1b4b;background:#f1f5f9;border-left:4px solid #4f46e5;padding:5px 10px;margin:16px 0 8px 0;border-radius:0 4px 4px 0;">${inlineFmt(l.slice(3))}</h2>`);
    } else if (l.startsWith("### ")) {
      if (inList) { parts.push("</ul>"); inList = false; }
      parts.push(`<h3 style="font-size:11px;font-weight:700;color:#334155;margin:10px 0 3px 0;">${inlineFmt(l.slice(4))}</h3>`);
    } else if (l.startsWith("- ") || l.startsWith("* ")) {
      if (!inList) { parts.push(`<ul style="margin:4px 0 10px 0;padding-left:18px;">`); inList = true; }
      parts.push(`<li style="font-size:10.5px;color:#334155;line-height:1.6;margin-bottom:3px;">${inlineFmt(l.slice(2))}</li>`);
    } else {
      if (inList) { parts.push("</ul>"); inList = false; }
      parts.push(`<p style="font-size:10.5px;color:#334155;line-height:1.6;margin:4px 0;">${inlineFmt(l)}</p>`);
    }
  }
  if (inList) parts.push("</ul>");

  const headerBand = `<div style="height:5px;background:linear-gradient(90deg,#4f46e5 0%,#7c3aed 50%,#06b6d4 100%);margin-bottom:18px;border-radius:2px;"></div>`;
  const brandBar = `<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:14px;padding-bottom:10px;border-bottom:1px solid #e2e8f0;"><span style="font-size:8.5px;font-weight:700;letter-spacing:1px;text-transform:uppercase;color:#4f46e5;background:#eef2ff;border:1px solid #c7d2fe;padding:2px 8px;border-radius:10px;">Executive Document</span><span style="font-size:9.5px;color:#64748b;font-family:monospace;">${dateStr}</span></div>`;
  const footerBar = `<div style="margin-top:28px;padding-top:10px;border-top:1px solid #e2e8f0;display:flex;justify-content:space-between;font-size:8.5px;color:#94a3b8;font-family:monospace;"><span>Generated by Techwiz GenAI</span><span>Confidential</span></div>`;

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>@page{margin:14mm 16mm;size:A4;}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;color:#0f172a;line-height:1.5;margin:0;padding:12px;background:#fff;}</style></head><body>${headerBand}${brandBar}${parts.join("\n")}${footerBar}</body></html>`;
}

export async function generateDocumentBuffer(extension, rawContent) {
  const ext = (extension || "txt").toLowerCase().trim();
  const content = (rawContent || "").trim();

  if (ext === "csv") return Buffer.from(content, "utf-8");

  if (ext === "xlsx") {
    const rows = content.split("\n").map((line) => line.split(",").map((c) => c.trim()));
    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet(rows);
    XLSX.utils.book_append_sheet(wb, ws, "Sheet1");
    return XLSX.write(wb, { type: "buffer", bookType: "xlsx" });
  }

  if (ext === "docx") {
    const lines = content.split("\n");
    const paragraphs = lines.map((line) => {
      const trimmed = line.trim();
      if (trimmed.startsWith("# ")) {
        return new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: trimmed.slice(2), bold: true, size: 30, color: "0F172A" })] });
      }
      if (trimmed.startsWith("## ")) {
        return new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text: trimmed.slice(3), bold: true, size: 24, color: "4F46E5" })] });
      }
      if (trimmed.startsWith("### ")) {
        return new Paragraph({ heading: HeadingLevel.HEADING_3, children: [new TextRun({ text: trimmed.slice(4), bold: true, size: 20, color: "334155" })] });
      }
      if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
        return new Paragraph({ bullet: { level: 0 }, children: [new TextRun({ text: trimmed.slice(2), size: 20, color: "334155" })] });
      }
      return new Paragraph({ children: [new TextRun({ text: line, size: 20, color: "334155" })] });
    });
    const doc = new Document({ sections: [{ properties: {}, children: paragraphs }] });
    return await Packer.toBuffer(doc);
  }

  if (ext === "pdf") {
    const html = formatDocumentToHtml(content);
    return await htmlPdf.generatePdf({ content: html }, { format: "A4" });
  }

  return Buffer.from(content, "utf-8");
}

export default { escapeHtml, formatDocumentToHtml, generateDocumentBuffer };
