import { VITE_API_URL } from "@/config/env";
import { logDebug } from "@/pages/Studio/logger";
import { respondToTool } from "@/pages/Studio/nesaTools";

const DATA_TOOLS = new Set(["deleteAsset", "previewAsset", "exportCallSummary", "getDashboardMetrics", "generateImage", "queryDocument"]);

async function authedGet(path, token) {
  const res = await fetch(`${VITE_API_URL}${path}`, { headers: token ? { Authorization: `Bearer ${token}` } : {} });
  return res.json();
}

export async function runNesaDataTool(ctx, d, cid) {
  const name = d.name;
  if (!DATA_TOOLS.has(name)) return;
  const { navigate, pathname } = ctx;
  const token = localStorage.getItem("token");
  const args = d.args || d;

  if (name === "deleteAsset") {
    if (!pathname.startsWith("/assets")) navigate("/assets");
    try {
      if (!token) respondToTool(cid, name, { status: "unauthorized" });
      else {
        const title = (args.title || d.title || "").toLowerCase();
        let assetId = args.assetId || d.assetId;
        if (!assetId || title) {
          const json = await authedGet("/assets", token);
          const match = title ? (json?.data || []).find((a) => (a.title || "").toLowerCase().includes(title)) : json?.data?.[0];
          if (match?.id) assetId = match.id;
        }
        if (assetId) {
          await fetch(`${VITE_API_URL}/assets/${assetId}`, { method: "DELETE", headers: { Authorization: `Bearer ${token}` } });
          window.dispatchEvent(new CustomEvent("asset_uploaded")); window.dispatchEvent(new CustomEvent("storage_updated"));
          respondToTool(cid, name, { success: true });
        } else respondToTool(cid, name, { status: "not_found" });
      }
    } catch (err) { logDebug("deleteAsset failed", err); respondToTool(cid, name, { status: "error" }); }
  }

  if (name === "previewAsset") {
    if (!pathname.startsWith("/assets")) navigate("/assets");
    try {
      if (!token) respondToTool(cid, name, { status: "unauthorized" });
      else {
        const q = (args.query || d.query || "").toLowerCase();
        const json = await authedGet("/assets", token);
        const list = json?.data || [];
        const match = q ? (list.find((a) => (a.title || "").toLowerCase().includes(q) || (a.format || "").toLowerCase().includes(q)) || list[0]) : list[0];
        if (match) {
          setTimeout(() => window.dispatchEvent(new CustomEvent("asset:preview", { detail: match })), 150);
          respondToTool(cid, name, { success: true, title: match.title });
        } else respondToTool(cid, name, { status: "not_found" });
      }
    } catch (err) { logDebug("previewAsset failed", err); respondToTool(cid, name, { status: "error" }); }
  }

  if (name === "exportCallSummary") {
    try {
      const reportTitle = args.title || d.title || "Executive Summary Report";
      if (token) {
        const sRes = await fetch(`${VITE_API_URL}/ai/sessions`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ persona: "writer" }) });
        const sData = await sRes.json(), sid = sData?.data?.id;
        if (sid) {
          const streamRes = await fetch(`${VITE_API_URL}/ai/sessions/${sid}/stream`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ prompt: "[DOC_REQ: pdf | # " + reportTitle + "\\n\\nCall & Session Executive Summary\\n- Generated by Techwiz GenAI]", model: "gemini-3.8-flash" }) });
          const text = await streamRes.text(), artMatch = text.match(/\[ARTIFACT:\s*pdf\s*\|\s*([^\]]+)\]/i), link = artMatch ? artMatch[1].trim() : "";
          window.dispatchEvent(new CustomEvent("asset_uploaded"));
          respondToTool(cid, name, { success: true, url: link, title: reportTitle });
        }
      }
    } catch (err) { logDebug("exportCallSummary failed", err); respondToTool(cid, name, { status: "error" }); }
  }

  if (name === "getDashboardMetrics") {
    try {
      const json = await authedGet("/dashboard/stats", token);
      respondToTool(cid, name, json?.data || { totalGenerations: 0, totalTokens: 0, totalAssets: 0 });
    } catch (err) { logDebug("getDashboardMetrics failed", err); respondToTool(cid, name, { status: "error" }); }
  }

  if (name === "generateImage") {
    try {
      const prompt = args.prompt || d.prompt || "";
      if (!pathname.startsWith("/studio")) navigate("/studio");
      const res = await fetch(`${VITE_API_URL}/ai/generate-image`, { method: "POST", headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify({ prompt }) });
      const json = await res.json();
      if (res.ok && json.success) {
        window.dispatchEvent(new CustomEvent("asset_uploaded")); window.dispatchEvent(new CustomEvent("studio:image_generated", { detail: { ...json, prompt } }));
        respondToTool(cid, name, { status: "success", url: json.imageUrl, imageUrl: json.imageUrl });
      } else respondToTool(cid, name, { status: "error" });
    } catch (err) { logDebug("generateImage failed", err); respondToTool(cid, name, { status: "error" }); }
  }

  if (name === "queryDocument") {
    try {
      const qry = args.query || d.query || "", docTitle = args.documentTitle || d.documentTitle || "";
      if (!token) { respondToTool(cid, name, { status: "unauthorized" }); return; }
      const res = await fetch(`${VITE_API_URL}/ai/query-document`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ query: qry, documentTitle: docTitle }) });
      const json = await res.json();
      if (res.ok && json.success) {
        window.dispatchEvent(new CustomEvent("studio:document_insight", { detail: json }));
        if (json.assetId) setTimeout(() => window.dispatchEvent(new CustomEvent("asset:preview", { detail: { id: json.assetId, title: json.sourceTitle } })), 300);
        respondToTool(cid, name, { status: "success", answer: json.answer, snippet: json.snippet, document: json.sourceTitle });
      } else respondToTool(cid, name, { status: "not_found", message: "No relevant document found" });
    } catch (err) { logDebug("queryDocument failed", err); respondToTool(cid, name, { status: "error", message: "No relevant document found" }); }
  }
}
